/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryOnRouteImport } from './routes/try-on'
import { Route as RetailerRouteImport } from './routes/retailer'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as WigIdRouteImport } from './routes/wig.$id'
import { Route as RetailerSignupRouteImport } from './routes/retailer_.signup'
import { Route as RetailerLoginRouteImport } from './routes/retailer_.login'
import { Route as PortalWidgetRouteImport } from './routes/portal.widget'
import { Route as PortalSettingsRouteImport } from './routes/portal.settings'
import { Route as PortalOnboardingRouteImport } from './routes/portal.onboarding'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PortalCatalogIndexRouteImport } from './routes/portal.catalog.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as PortalCatalogNewRouteImport } from './routes/portal.catalog.new'
import { Route as PortalCatalogWigIdRouteImport } from './routes/portal.catalog.$wigId'
import { Route as EmbedWidgetTokenRouteImport } from './routes/embed.widget.$token'
import { Route as AuthenticatedAppWishlistRouteImport } from './routes/_authenticated.app.wishlist'
import { Route as AuthenticatedAppTryOnRouteImport } from './routes/_authenticated.app.try-on'
import { Route as AuthenticatedAppStyleQuizRouteImport } from './routes/_authenticated.app.style-quiz'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppCatalogRouteImport } from './routes/_authenticated.app.catalog'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TryOnRoute = TryOnRouteImport.update({
  id: '/try-on',
  path: '/try-on',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerRoute = RetailerRouteImport.update({
  id: '/retailer',
  path: '/retailer',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const WigIdRoute = WigIdRouteImport.update({
  id: '/wig/$id',
  path: '/wig/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerSignupRoute = RetailerSignupRouteImport.update({
  id: '/retailer_/signup',
  path: '/retailer/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerLoginRoute = RetailerLoginRouteImport.update({
  id: '/retailer_/login',
  path: '/retailer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalWidgetRoute = PortalWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSettingsRoute = PortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOnboardingRoute = PortalOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCatalogIndexRoute = PortalCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalCatalogNewRoute = PortalCatalogNewRouteImport.update({
  id: '/catalog/new',
  path: '/catalog/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCatalogWigIdRoute = PortalCatalogWigIdRouteImport.update({
  id: '/catalog/$wigId',
  path: '/catalog/$wigId',
  getParentRoute: () => PortalRoute,
} as any)
const EmbedWidgetTokenRoute = EmbedWidgetTokenRouteImport.update({
  id: '/embed/widget/$token',
  path: '/embed/widget/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWishlistRoute =
  AuthenticatedAppWishlistRouteImport.update({
    id: '/app/wishlist',
    path: '/app/wishlist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppTryOnRoute = AuthenticatedAppTryOnRouteImport.update({
  id: '/app/try-on',
  path: '/app/try-on',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppStyleQuizRoute =
  AuthenticatedAppStyleQuizRouteImport.update({
    id: '/app/style-quiz',
    path: '/app/style-quiz',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppCatalogRoute = AuthenticatedAppCatalogRouteImport.update({
  id: '/app/catalog',
  path: '/app/catalog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/retailer': typeof RetailerRoute
  '/try-on': typeof TryOnRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/widget': typeof PortalWidgetRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/signup': typeof RetailerSignupRoute
  '/wig/$id': typeof WigIdRoute
  '/portal/': typeof PortalIndexRoute
  '/app/catalog': typeof AuthenticatedAppCatalogRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/style-quiz': typeof AuthenticatedAppStyleQuizRoute
  '/app/try-on': typeof AuthenticatedAppTryOnRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/embed/widget/$token': typeof EmbedWidgetTokenRoute
  '/portal/catalog/$wigId': typeof PortalCatalogWigIdRoute
  '/portal/catalog/new': typeof PortalCatalogNewRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/portal/catalog/': typeof PortalCatalogIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/pricing': typeof PricingRoute
  '/retailer': typeof RetailerRoute
  '/try-on': typeof TryOnRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/widget': typeof PortalWidgetRoute
  '/retailer/login': typeof RetailerLoginRoute
  '/retailer/signup': typeof RetailerSignupRoute
  '/wig/$id': typeof WigIdRoute
  '/portal': typeof PortalIndexRoute
  '/app/catalog': typeof AuthenticatedAppCatalogRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/style-quiz': typeof AuthenticatedAppStyleQuizRoute
  '/app/try-on': typeof AuthenticatedAppTryOnRoute
  '/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/embed/widget/$token': typeof EmbedWidgetTokenRoute
  '/portal/catalog/$wigId': typeof PortalCatalogWigIdRoute
  '/portal/catalog/new': typeof PortalCatalogNewRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/portal/catalog': typeof PortalCatalogIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/catalog': typeof CatalogRoute
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/retailer': typeof RetailerRoute
  '/try-on': typeof TryOnRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/onboarding': typeof PortalOnboardingRoute
  '/portal/settings': typeof PortalSettingsRoute
  '/portal/widget': typeof PortalWidgetRoute
  '/retailer_/login': typeof RetailerLoginRoute
  '/retailer_/signup': typeof RetailerSignupRoute
  '/wig/$id': typeof WigIdRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/app/catalog': typeof AuthenticatedAppCatalogRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/style-quiz': typeof AuthenticatedAppStyleQuizRoute
  '/_authenticated/app/try-on': typeof AuthenticatedAppTryOnRoute
  '/_authenticated/app/wishlist': typeof AuthenticatedAppWishlistRoute
  '/embed/widget/$token': typeof EmbedWidgetTokenRoute
  '/portal/catalog/$wigId': typeof PortalCatalogWigIdRoute
  '/portal/catalog/new': typeof PortalCatalogNewRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/portal/catalog/': typeof PortalCatalogIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/portal'
    | '/pricing'
    | '/retailer'
    | '/try-on'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/checkout/success'
    | '/portal/billing'
    | '/portal/onboarding'
    | '/portal/settings'
    | '/portal/widget'
    | '/retailer/login'
    | '/retailer/signup'
    | '/wig/$id'
    | '/portal/'
    | '/app/catalog'
    | '/app/profile'
    | '/app/style-quiz'
    | '/app/try-on'
    | '/app/wishlist'
    | '/embed/widget/$token'
    | '/portal/catalog/$wigId'
    | '/portal/catalog/new'
    | '/app/'
    | '/portal/catalog/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/pricing'
    | '/retailer'
    | '/try-on'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/checkout/success'
    | '/portal/billing'
    | '/portal/onboarding'
    | '/portal/settings'
    | '/portal/widget'
    | '/retailer/login'
    | '/retailer/signup'
    | '/wig/$id'
    | '/portal'
    | '/app/catalog'
    | '/app/profile'
    | '/app/style-quiz'
    | '/app/try-on'
    | '/app/wishlist'
    | '/embed/widget/$token'
    | '/portal/catalog/$wigId'
    | '/portal/catalog/new'
    | '/app'
    | '/portal/catalog'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/catalog'
    | '/portal'
    | '/pricing'
    | '/retailer'
    | '/try-on'
    | '/auth/callback'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/checkout/success'
    | '/portal/billing'
    | '/portal/onboarding'
    | '/portal/settings'
    | '/portal/widget'
    | '/retailer_/login'
    | '/retailer_/signup'
    | '/wig/$id'
    | '/portal/'
    | '/_authenticated/app/catalog'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/style-quiz'
    | '/_authenticated/app/try-on'
    | '/_authenticated/app/wishlist'
    | '/embed/widget/$token'
    | '/portal/catalog/$wigId'
    | '/portal/catalog/new'
    | '/_authenticated/app/'
    | '/portal/catalog/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CatalogRoute: typeof CatalogRoute
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  RetailerRoute: typeof RetailerRoute
  TryOnRoute: typeof TryOnRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  RetailerLoginRoute: typeof RetailerLoginRoute
  RetailerSignupRoute: typeof RetailerSignupRoute
  WigIdRoute: typeof WigIdRoute
  EmbedWidgetTokenRoute: typeof EmbedWidgetTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try-on': {
      id: '/try-on'
      path: '/try-on'
      fullPath: '/try-on'
      preLoaderRoute: typeof TryOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer': {
      id: '/retailer'
      path: '/retailer'
      fullPath: '/retailer'
      preLoaderRoute: typeof RetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/wig/$id': {
      id: '/wig/$id'
      path: '/wig/$id'
      fullPath: '/wig/$id'
      preLoaderRoute: typeof WigIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer_/signup': {
      id: '/retailer_/signup'
      path: '/retailer/signup'
      fullPath: '/retailer/signup'
      preLoaderRoute: typeof RetailerSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer_/login': {
      id: '/retailer_/login'
      path: '/retailer/login'
      fullPath: '/retailer/login'
      preLoaderRoute: typeof RetailerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/widget': {
      id: '/portal/widget'
      path: '/widget'
      fullPath: '/portal/widget'
      preLoaderRoute: typeof PortalWidgetRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/settings': {
      id: '/portal/settings'
      path: '/settings'
      fullPath: '/portal/settings'
      preLoaderRoute: typeof PortalSettingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/onboarding': {
      id: '/portal/onboarding'
      path: '/onboarding'
      fullPath: '/portal/onboarding'
      preLoaderRoute: typeof PortalOnboardingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/catalog/': {
      id: '/portal/catalog/'
      path: '/catalog'
      fullPath: '/portal/catalog/'
      preLoaderRoute: typeof PortalCatalogIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/catalog/new': {
      id: '/portal/catalog/new'
      path: '/catalog/new'
      fullPath: '/portal/catalog/new'
      preLoaderRoute: typeof PortalCatalogNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/catalog/$wigId': {
      id: '/portal/catalog/$wigId'
      path: '/catalog/$wigId'
      fullPath: '/portal/catalog/$wigId'
      preLoaderRoute: typeof PortalCatalogWigIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/embed/widget/$token': {
      id: '/embed/widget/$token'
      path: '/embed/widget/$token'
      fullPath: '/embed/widget/$token'
      preLoaderRoute: typeof EmbedWidgetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/wishlist': {
      id: '/_authenticated/app/wishlist'
      path: '/app/wishlist'
      fullPath: '/app/wishlist'
      preLoaderRoute: typeof AuthenticatedAppWishlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/try-on': {
      id: '/_authenticated/app/try-on'
      path: '/app/try-on'
      fullPath: '/app/try-on'
      preLoaderRoute: typeof AuthenticatedAppTryOnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/style-quiz': {
      id: '/_authenticated/app/style-quiz'
      path: '/app/style-quiz'
      fullPath: '/app/style-quiz'
      preLoaderRoute: typeof AuthenticatedAppStyleQuizRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/catalog': {
      id: '/_authenticated/app/catalog'
      path: '/app/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AuthenticatedAppCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppCatalogRoute: typeof AuthenticatedAppCatalogRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppStyleQuizRoute: typeof AuthenticatedAppStyleQuizRoute
  AuthenticatedAppTryOnRoute: typeof AuthenticatedAppTryOnRoute
  AuthenticatedAppWishlistRoute: typeof AuthenticatedAppWishlistRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppCatalogRoute: AuthenticatedAppCatalogRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppStyleQuizRoute: AuthenticatedAppStyleQuizRoute,
  AuthenticatedAppTryOnRoute: AuthenticatedAppTryOnRoute,
  AuthenticatedAppWishlistRoute: AuthenticatedAppWishlistRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalBillingRoute: typeof PortalBillingRoute
  PortalOnboardingRoute: typeof PortalOnboardingRoute
  PortalSettingsRoute: typeof PortalSettingsRoute
  PortalWidgetRoute: typeof PortalWidgetRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalCatalogWigIdRoute: typeof PortalCatalogWigIdRoute
  PortalCatalogNewRoute: typeof PortalCatalogNewRoute
  PortalCatalogIndexRoute: typeof PortalCatalogIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBillingRoute: PortalBillingRoute,
  PortalOnboardingRoute: PortalOnboardingRoute,
  PortalSettingsRoute: PortalSettingsRoute,
  PortalWidgetRoute: PortalWidgetRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalCatalogWigIdRoute: PortalCatalogWigIdRoute,
  PortalCatalogNewRoute: PortalCatalogNewRoute,
  PortalCatalogIndexRoute: PortalCatalogIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CatalogRoute: CatalogRoute,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  RetailerRoute: RetailerRoute,
  TryOnRoute: TryOnRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  RetailerLoginRoute: RetailerLoginRoute,
  RetailerSignupRoute: RetailerSignupRoute,
  WigIdRoute: WigIdRoute,
  EmbedWidgetTokenRoute: EmbedWidgetTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
